config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :user do
    end
  end
  
  root 'dashboard#index'
  
  get 'first_login' => 'dashboard#first_login', as: :first_login
  get 'first_event' => 'dashboard#first_event', as: :first_event
  
  get 'l/show/:id' => 'dashboard#show_location', as: :show_location
  get 'p/show/:id' => 'dashboard#show_performer', as: :show_performer
  get 'o/show/:id' => 'dashboard#show_organizer', as: :show_organizer
  
  get 'l/:id/edit_images' => 'location#edit_images'
  get 'p/:id/edit_images' => 'performer#edit_images'
  get 'e/:id/edit_images' => 'event#edit_images'
  get 'o/:id/edit_images' => 'organizer#edit_images'
  get 'o/:id/edit_profile_image' => 'organizer#edit_profile_image'
  
  get 'l/:id/events' => 'location#events'
  get 'p/:id/events' => 'performer#events'
  get 'o/:id/events' => 'organizer#events'
  
  get 'l/:id/edit_informations' => 'location#edit_informations'
  get 'p/:id/edit_informations' => 'performer#edit_informations'
  get 'o/:id/edit_informations' => 'organizer#edit_informations'
  get 'e/:id/edit' => 'event#edit'

  patch 'l/:id/edit_informations' => 'location#update_informations', as: :edit_location_informations
  patch 'p/:id/edit_informations' => 'performer#update_informations', as: :edit_performer_informations
  patch 'o/:id/edit_informations' => 'organizer#update_informations', as: :edit_organizer_informations
  patch 'e/:id/edit' => 'event#update', as: :update_event
  
  get 'l/:id/share' => 'location#share'
  get 'p/:id/share' => 'performer#share'
  get 'o/:id/share' => 'organizer#share'
  get 'e/:id/share' => 'event#share'
  
  get 'l/:id/social_links' => 'location#social_links'
  get 'p/:id/social_links' => 'performer#social_links'
  get 'o/:id/social_links' => 'organizer#social_links'
  get 'e/:id/social_links' => 'event#social_links'
  
  get 'p/:id/requests' => 'performer#requests'
  get 'o/:id/requests' => 'organizer#requests'
  
  get 'e/:id/tickets' => 'event#tickets'
  get 'e/:id/performer' => 'event#edit_performer'
  get 'e/:id/premium' => 'event#edit_premium'
  get 'e/:id/statistiken' => 'event#statistiken'
  patch 'e/:id/toggle-online' => 'event#toggle_online'
  
  
  patch 'l/:id/social_links' => 'location#edit_social_links', as: :edit_location_social_links
  patch 'p/:id/social_links' => 'performer#edit_social_links', as: :edit_performer_social_links
  patch 'o/:id/social_links' => 'organizer#edit_social_links', as: :edit_organizer_social_links
  patch 'e/:id/social_links' => 'event#update_social_links', as: :update_event_social_links
  
  get 'l/:id/opening_hours' => 'location#opening_hours'
  patch 'l/:id/opening_hours' => 'location#update_opening_hours', as: :update_opening_hours
  
  post 'l/create_from_event' => 'location#create_from_event', as: :create_location_from_event
  get 'l/search_from_event' => 'location#search_from_event'

  post 'p/create_from_event' => 'performer#create_from_event', as: :create_performer_from_event
  get 'p/search_from_event' => 'performer#search_from_event'
  post 'performer-request' => 'performer#performer_request'
  patch 'performer-request/:id' => 'performer#update_performer_request'
  delete 'delete-performer-request' => 'performer#delete_performer_request', as: :delete_performer_request
  
  post 'o/create_from_event' => 'organizer#create_from_event', as: :create_organizer_from_event
  get 'o/search_from_event' => 'organizer#search_from_event'
  post 'organizer-request' => 'organizer#organizer_request'
  patch 'organizer-request/:id' => 'organizer#update_organizer_request'
  delete 'delete-organizer-request' => 'organizer#delete_organizer_request', as: :delete_organizer_request
  
  
  get 'einstellungen' => 'dashboard#settings'
  get 'einstellungen/profiles' => 'dashboard#profiles'
  get 'einstellungen/abo' => 'dashboard#abo'
  get 'einstellungen/abo/plans' => 'payment#plans'
  get 'einstellungen/abo/bezahlen' => 'payment#payment_method'
  get 'statistiken' => 'dashboard#statistiken'
  get 'select_abo' => 'payment#select_abo', as: :select_abo
  
  get 'success' => 'payment#success'  
  get 'cancel' => 'payment#cancel'
  
  post 'webhook/customer_updated' => 'payment#customer_updated'
  post 'webhook/charge' => 'payment#charge'
  post 'webhook/invoice_created' => 'payment#invoice_created'
  
  post 'pageview' => 'page_view#create'
  
  get 'neue-location' => 'dashboard#new_location'
  get 'neuer-performer' =>'dashboard#new_performer'
  get 'neues-event' => 'dashboard#new_event'
  get 'neuer-organizer' => 'dashboard#new_organizer'
  
  get 'fertigstellen/:type/:id' => 'dashboard#fertigstellen'
  
  get 'event-bearbeiten/:id' => 'dashboard#edit_event'
  get 'performer-bearbeiten/:id' => 'dashboard#edit_performer'

  post 'event/create' => 'event#create_event1', as: :create_event1
  post 'event/:id/add_images' =>  'event#add_images'
  post 'event/select-plan/:id' => 'event#select_plan'
  patch 'event/create3/:id' =>  'event#create_event3', as: :create_event3
  
  post 'create-ticket' =>  'ticket#create', as: :create_ticket
  
  post 'create-link' =>  'social_link#create', as: :create_link
  
  post 'location/create' => 'location#create_location1', as: :create_location1
  post 'location/:id/add_images' =>  'location#add_images'
  patch 'location/create3/:id' =>  'location#create_location3', as: :create_location3
  
  post 'performer/create' => 'performer#create_performer1', as: :create_performer1
  post 'performer/:id/add_image' =>  'performer#add_image'
  
  post 'organizer/create' => 'organizer#create_organizer1', as: :create_organizer1
  post 'organizer/:id/add_image' =>  'organizer#add_image'
  post 'organizer/:id/add_profile_image' =>  'organizer#add_profile_image'
  
  post 'opening_hour/create' => 'opening_hour#create'
  post 'social_link/create' => 'social_link#create'
  post 'ticket/create' => 'ticket#create'
  
  get 'performer/search' => 'event#search_performer'
  post 'performer/invite' => 'event#invite_performer', as: :invite_performer
  post 'performer/create' => 'performer#create'
  
  get 'organizer/search' => 'event#search_organizer'
  post 'organizer/invite' => 'event#invite_organizer', as: :invite_organizer
  post 'organizer/create' => 'organizer#create'
  
  patch 'event/edit/:id' => 'event#edit', as: :edit_event
  patch 'location/edit/:id' => 'location#edit'
  patch 'opening_hour/edit/:id' => 'opening_hour#edit'
  patch 'social_link/edit/:id' => 'social_link#edit'
  patch 'ticket/edit/:id' => 'ticket#edit'
  patch 'performer/edit/:id' => 'performer#edit', as: :edit_performer
  
  delete 'event/delete/:id' => 'event#delete', as: :delete_event
  delete 'location/delete/:id' => 'location#delete', as: :delete_location
  delete 'delete_image/:id' => 'dashboard#delete_image', as: :delete_image
  delete 'opening_hour/delete/:id' => 'opening_hour#delete'
  delete 'social_link/delete/:id' => 'social_link#destroy', as: :destroy_link
  delete 'ticket/delete/:id' => 'ticket#destroy', as: :destroy_ticket
  delete 'performer/delete/:id' => 'performer#delete', as: :delete_performer
  delete 'organizer/delete/:id' => 'organizer#delete', as: :delete_organizer
  
  devise_for :users
  
  patch 'update_invoice_mail' => 'dashboard#invoice_email', as: :update_invoice_mail
  
  # Event, Location & Performer Views
  
  get 'location/:path' => 'public_view#location'
  get 'performer/:path' => 'public_view#performer'
  get 'organizer/:path' => 'public_view#organizer'
  get 'event/:path' => 'public_view#event'
  get 'event/:path/tickets' => 'public_view#tickets'
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController  
  before_action :authenticate_user!
  layout 'dashboard'
  
  def first_login
    
  end
  
  def first_event
    
  end
  
  def index
    finish_onboarding
    onboarding_done?
    
    @user = current_user
    
    if params[:profile] != nil
      if params[:type] == 'location'
        @profile = Location.find(params[:profile])
        @type = 'location'
      elsif params[:type] == 'performer'
        @profile = Performer.find(params[:profile])
        @type = 'performer'
      else
        @profile = Organizer.find(params[:profile])
        @type = 'organizer'
      end
    else 
      if @user.locations.any? 
        @profile = @user.locations.first
        @type = 'location'
      elsif @user.performers.any?
        @profile = @user.performers.first
        @type = 'performer'
      else
        @profile = @user.organizers.first
        @type = 'organizer'
      end
    end
  end
  
  def new_location
    barrier_locations
    
    @user = current_user
    @location = Location.new
    @resource = "Ihre Location"
  end
  
  def new_performer
    barrier_performer
    
    @user = current_user
    @performer = Performer.new
    @resource = "Ihr Performer"
  end
  
  def new_organizer  
    @user = current_user
    @organizer = Organizer.new
    @resource = "Ihr Organizer"
  end
  
  def new_event
    barrier_events
    
    if params[:profile] != nil
      if params[:type] == 'location'
        @location = Location.find(params[:profile])
        @profile = @location.id
        @type = 'location'
      elsif params[:type] == 'performer'
        @performer = Performer.find(params[:profile])
        @profile = @performer.id
        @type = 'performer'
      else
        @organizer = Organizer.find(params[:profile])
        @profile = @organizer.id
        @type = 'organizer'
      end
    end
    
    @user = current_user
    @event = Event.new
    @resource = "Ihre Veranstaltung"
    
  end
  
  def edit_event
    @event = Event.find(params[:id])
  end
  
  def edit_performer
    @performer = Performer.find(params[:id])
  end
  
  def show_location
    @profile = Location.find(params[:id])
    
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/show_location' }
    end
  end
  
  def show_performer
    @profile = Performer.find(params[:id])
    
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/show_performer' }
    end
  end
  
  def show_organizer
    @profile = Organizer.find(params[:id])
    
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/show_organizer' }
    end
  end
  
  def settings
    @user = current_user
  end
  
  def delete_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/image_destroyed' }
    end
  end
  
  def profiles
    @user = current_user
    
  end
  
  def abo
    @user = current_user    
  end
  
  def invoice_email
    @user = current_user
    @user.bill_per_email = !@user.bill_per_email
    if @user.save!
      respond_to do |format|
        format.js { render :js => "$('.toggle_check').toggleClass('active');" }
      end
    else
      respond_to do |format|
        format.js { render :js => "alert('danger', 'Es ist ein Fehler aufgetretten.')" }
      end
    end
  end
  
  def statistiken
    @user = current_user
  end
  
  def fertigstellen
    
    case params[:type]
      when 'p'
        @resource = Performer.find(params[:id])
        @header = 'Performer'
      when 'e'
        @resource = Event.find(params[:id])
        @header = 'Event'
      when 'l'
        @resource = Location.find(params[:id])
        @header = 'Location'
      when 'o'
        @resource = Organizer.find(params[:id])
        @header = 'Veranstalter'
    end
  end
  
private
  
  def has_profile?
    if !current_user.locations.any? && !current_user.performers.any?
      redirect_to first_login_path
    end
  end
  
  def finish_onboarding
    if params[:onboardingfinished]
      current_user.onboarding = true
      current_user.save!
    end
  end
  
  def onboarding_done?
    if !current_user.locations.any? && !current_user.performers.any? && !current_user.organizers.any?
      redirect_to first_login_path
      return
    else
      if current_user.onboarding != true
        if current_user.events.length == 0
          redirect_to first_event_path
        else
          redirect_to select_abo_path
        end
      end
    end
  end
  
  def barrier_locations
    case current_user.plan
      when "free"
        if current_user.locations.length > 0
          redirect_to 
        end
      when "Gold"
        if current_user.locations.length >= 10
          redirect_to 
        end
      when "Platin"
        return
    end
  end
  
  def barrier_performer
    case current_user.plan
      when "free"
        if current_user.performers.length > 3
          redirect_to 
        end
      when "Gold"
        if current_user.performers.length > 10
          redirect_to 
        end
      when "Platin"
        return
    end
  end
  
  def barrier_events
    case current_user.plan
      when "free"
        if current_user.events.length >= 3
          redirect_to 
        end
      when "Gold"
        if current_user.events.length >= 100
          redirect_to 
        end
      when "Platin"
      
    end
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/abo.html.erb
<%= render 'dashboard/shared/header3', header: 'Abonnement' %>
<div class="container">
  <div class="abo-container">
    <div class="top">
      <h2>Abonnement</h2>
      <% if @user.plan == "free" %>
        <a href="/einstellungen/abo/plans">bearbeiten</a>
      <% else %>
        <a href="mailto:kontakt@the-radr.com?subject=Abonnement%20aktualisieren%20User%20ID:<%= @user.id %>">Support kontaktieren</a>
      <% end %>
    </div>
    <div id="abonnement">
      <img src="/images/<%= @user.plan %>.png" alt="Free"> <span><%= @user.plan_str %></span>
    </div>
  </div>
  
  <div class="abo-container">
    <div class="top">
      <h2>Bezahlmethode</h2>
    </div>
    <div id="bezahlmethode">
      <% if @user.plan != "free" %>
        <img src="/images/paid/<%= @user.cc_brand %>.svg" alt="Payment">      
        <svg width="174px" height="13px" viewBox="0 0 174 13" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <g transform="translate(0.000000, -2.000000)" fill="#000000">
                  <circle cx="4" cy="9" r="4"></circle>
                  <circle cx="20" cy="9" r="4"></circle>
                  <circle cx="68" cy="9" r="4"></circle>
                  <circle cx="36" cy="9" r="4"></circle>
                  <circle cx="84" cy="9" r="4"></circle>
                  <circle cx="52" cy="9" r="4"></circle>
                  <circle cx="100" cy="9" r="4"></circle>
                  <text font-family="hero-new" font-size="14" font-weight="normal" line-spacing="18" letter-spacing="8">
                    <tspan x="116" y="15"><%= @user.cc_last_four %></tspan>
                  </text>
              </g>
          </g>
      </svg>
      <% end %>
    </div>
  </div>
  
  <div class="abo-container">
    <div class="top">
      <h2>Rechnungen</h2>
    </div>
    <div id="rechnungen">
        <% @user.invoices.each do |invoice| %>
          <div class="invoice">
            <span><%= invoice.date_str %></span>
            <a target="_blank" href="<%= invoice.pdf %>">PDF herunterladen</a>
          </div>
        <% end %>
        <% if @user.invoices.length == 0 %>
          <div class="invoice inactive">
            <span>Keine Rechnung vorhanden</span>
          </div>
        <% end %>
    </div>
      <%= form_for(@user, :html => {role: "form", id: "rechnung_email"}, url: update_invoice_mail_url) do |f| %>
        <span>Rechnung per Email senden</span>
        <button class="toggle_check<% if @user.bill_per_email %> active<% end %>"></button>
      <% end %>    
    </div>
  </div>
<script>
    $(document).ready(function() { 
            $('#rechnung_email').ajaxForm();
        });
</script>

app/views/dashboard/edit_event.html.erb
<%= form_for(@event, :html => {role: "form", :multipart => true}, url: edit_event_path) do |f| %>
  <div class="form-group">
            <label for="attachment" class="custom-file-label" >Image</label>
            <input id="attachment" class="custom-file-input" name="attachment" type="file" />
          </div>
  <%= f.submit %>
<% end %>

app/views/dashboard/edit_performer.html.erb
<%= form_for(@performer, :html => {role: "form", :multipart => true}, url: edit_performer_path) do |f| %>
  <div class="form-group">
            <label for="attachment" class="custom-file-label" >Image</label>
            <input id="attachment" class="custom-file-input" name="attachment" type="file" />
          </div>
  <%= f.submit %>
<% end %>

app/views/dashboard/first_event.html.erb
<div class="febg">
  <h1>Erstes Event erstellen</h1>
  <div class="febg-footer">
    <a href="/neues-event" class="btn-primary">Event erstellen</a>
    <a href="/select_abo" class="btn-primary btn-secondary">Weiter</a>
  </div>
</div>
<script src="https://unpkg.com/dropzone"></script>
<script src="https://unpkg.com/cropperjs"></script>

app/views/dashboard/new_organizer.html.erb
<%= render 'dashboard/shared/header3', header: 'Neuer Veranstalter'%>
<div class="container">
  <h1 class="form-h1">Neuer Veranstalter</h1>
  <div class="form-accordion event-accordion">
    <div id="accordion1" class="accordion-inner active">
      <div class="accordion-header">
        <span class="point">          
          <svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <circle fill="currentColor" cx="10" cy="10" r="10"></circle>
              <text font-family="hero-new" font-size="14" font-weight="400" fill="#FFFFFF">
                  <tspan x="6.766" y="15">1</tspan>
              </text>
            </g>
          </svg>
        </span>
        <h2>Name, Kategorie & Beschreibung</h2>
      </div>
      <div class="accordion-body">
        <%= form_for(@organizer, :html => {role: "form", id: "form1", style: "overflow-x: hidden;"}, url: create_organizer1_path) do |f| %>
          <div class="form-group">
            <label for="organizername">Name</label>
            <input type="text" class="form-control" name="organizername" id="organizername" aria-describedby="organizerHelp" placeholder="Veranstalter" required>
          </div>
          <div class="form-group">
            <label for="location">Kategorie</label>
            <%= f.select(:category, Organizer.categories, {}, {class: "form-control"}) %>
            <small id="locationHelp" class="form-text text-muted">Wählen Sie eine Kategorie aus.</small>
          </div>
          <div class="form-group">
            <label for="description">Beschreibung</label>
            <textarea class="form-control" id="description" aria-describedby="descriptionHelp" name="description" rows="3"></textarea>
          </div>
        <% end %>
      </div>
    </div>
    <div id="accordion2" class="accordion-inner">
      <div class="accordion-header">
        <span class="point">          
          <svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <circle fill="currentColor" cx="10" cy="10" r="10"></circle>
              <text font-family="hero-new" font-size="14" font-weight="400" fill="#FFFFFF">
                  <tspan x="6.766" y="15">2</tspan>
              </text>
            </g>
          </svg>
        </span>
        <h2>Profilbild hochladen</h2>
      </div>
      <div class="accordion-body" id="imageupload">
        <form action="/performer/4/add_images" class="dropzone" id="myDropzone"></form>
        <label>Laden Sie Ihr Profilbild hier hoch. Sollte der Ladebalken nicht verschwinden drücken Sie einfach weiter.</label>
      </div>
    </div>
    <div id="accordion3" class="accordion-inner">
      <div class="accordion-header">
        <span class="point">          
          <svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <circle fill="currentColor" cx="10" cy="10" r="10"></circle>
              <text font-family="hero-new" font-size="14" font-weight="400" fill="#FFFFFF">
                  <tspan x="6.766" y="15">3</tspan>
              </text>
            </g>
          </svg>
        </span>
        <h2>Social Links</h2>
      </div>
      <div class="accordion-body">
        <div id="linkContainer">
          <%= form_for(SocialLink.new, :html => {role: "form", id: "newlink"}, url: create_link_path) do |f| %>
            <h5 style="margin-bottom: 10px !important;">Social Link</h5>
            <input type="text" name="organizer_id" id="organizerid" value="1" hidden>
            <input type="text" name="container" value="linkContainer" hidden>
              <div class="input-group input-group-sm" style="margin-bottom: 5px;">
                <%= f.text_field :url, placeholder: 'URL', class: "form-control" %>
              </div>
              <div class="input-group input-group-sm" style="margin-bottom: 5px;">
                <%= f.select(:channel, SocialLink.channels, {}, {class: "form-control"}) %>
              </div>
              <div class="input-group input-group-sm" style="margin-bottom: 5px;">
                <%= f.submit "Link erstellen", class: "btn btn-primary" %>
              </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
  </div>
<div class="footer">
  <a href='' class="footer-link" id="button1">Weiter</a> 
  <a href='' class="footer-link" id="button2" style="display: none;">Weiter</a>
  <a href='' class="footer-link" id="button3" style="display: none;">Fertigstellen</a>
</div>
<!-- Dropzone JS -->
<script src="https://unpkg.com/dropzone"></script>
<script src="https://unpkg.com/cropperjs"></script>
<script>
  var organizer_id = 0;
  Dropzone.autoDiscover = false;
  $(document).ready(function(){
   myDropzone = new Dropzone("#myDropzone", {
       url: "/organizer/1/add_image",
       maxFiles: 1,
       transformFile: function(file, done) {
        // Create Dropzone reference for use in confirm button click handler
        var myDropZone = this;
        // Create the image editor overlay
        var editor = document.createElement('div');
        editor.style.position = 'fixed';
        editor.style.left = 0;
        editor.style.right = 0;
        editor.style.top = 0;
        editor.style.bottom = 0;
        editor.style.zIndex = 9999;
        editor.style.backgroundColor = '#000';
        document.body.appendChild(editor);
        // Create confirm button at the top left of the viewport
        var buttonConfirm = document.createElement('button');
        buttonConfirm.className = 'btn btn-primary';
        buttonConfirm.style.position = 'absolute';
        buttonConfirm.style.right = '10px';
        buttonConfirm.style.top = '10px';
        buttonConfirm.style.zIndex = 9999;
        buttonConfirm.textContent = 'Confirm';
        editor.appendChild(buttonConfirm);
        buttonConfirm.addEventListener('click', function() {
          // Get the canvas with image data from Cropper.js
          var canvas = cropper.getCroppedCanvas({
            maxWidth: 800,
            maxHeight: 800
          });
          // Turn the canvas into a Blob (file object without a name)
          canvas.toBlob(function(blob) {
            // Create a new Dropzone file thumbnail
            myDropZone.createThumbnail(
              blob,
              myDropZone.options.thumbnailWidth,
              myDropZone.options.thumbnailHeight,
              myDropZone.options.thumbnailMethod,
              false, 
              function(dataURL) {

                // Update the Dropzone file thumbnail
                myDropZone.emit('thumbnail', file, dataURL);
                // Return the file to Dropzone
                done(blob);
            });
          });
          // Remove the editor from the view
          document.body.removeChild(editor);
        });
        // Create an image node for Cropper.js
        var image = new Image();
        image.src = URL.createObjectURL(file);
        editor.appendChild(image);

      // Create Cropper.js
      var cropper = new Cropper(image, { aspectRatio: 1.7 });
    },
        init: function() {
        this.on("processing", function(file) {
          this.options.url = 'organizer/' + organizer_id + '/add_image';
        });
      }

    });
    $('.dz-default').html('Dateien nach hier ziehen oder klicken zum hochladen');  
  });
</script>
<!-- Step 1 -->
<script>
  $('#button1').on('click', function(event){
    event.preventDefault();
    $('#form1').submit();
 });
// Step 2  
 $('#button2').on('click', function(event){
    event.preventDefault();
    $('#button2').remove();
    $('#button3').css('display', 'block');
    $("#accordion2").removeClass('active').addClass('done');
    $("#accordion3").addClass('active');
 });
// Step 3  
  $('#button3').on('click', function(event){
    event.preventDefault();
    $('#button3').remove();
    window.location.replace("/fertigstellen/o/" + organizer_id);
 });
  
  $(document).ready(function() { 
            // bind 'myForm' and provide a simple callback function 
            $('#form1').ajaxForm();
            $('#newlink').ajaxForm();
        });
</script>
<script src="/jquery.form.min.js"></script>
<script>
 function changeAccordion(slide){
   $('.accordion-inner').removeClass('active');
   $('#accordion' + slide).addClass('active');
 };
</script>

app/views/dashboard/payment_method.html.erb
<%= render 'dashboard/shared/header3', header: 'Bezahlmethode' %>
<div class="container">
  
</div>

app/views/dashboard/profiles.html.erb
<%= render 'dashboard/shared/header3', header: 'Profile bearbeiten' %>
<div class="container">
  <% @user.locations.each do |profile| %>
    <div class="card" data-id="location<%= profile.id %>">
      <div class="card-header">
        <%= profile.name %>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="/?profile=<%= profile.id %>&type=location">Profil anzeigen</a></li>
        <li class="list-group-item" hidden><a href="">Profil Übertragen</a></li>
        <li class="list-group-item"><%= button_to "Profil löschen", delete_location_url(profile.id), data: { confirm: "Sind Sie sich wirklich sicher?" }, style: "padding: 0; color: #337ab7; font-size: 14px; font-family: hero-new;", method: :delete, :remote => true %></li>
      </ul>
    </div>
  <% end %>
  <% @user.performers.each do |profile| %>
    <div class="card" data-id="performer<%= profile.id %>" >
      <div class="card-header">
        <%= profile.name %>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="/?profile=<%= profile.id %>&type=performer">Profil anzeigen</a></li>
        <li class="list-group-item" hidden><a href="">Profil Übertragen</a></li>
        <li class="list-group-item"><%= button_to "Profil löschen", delete_performer_url(profile.id), data: { confirm: "Sind Sie sich wirklich sicher?" }, style: "padding: 0; color: #337ab7; font-size: 14px; font-family: hero-new;", method: :delete, :remote => true %></li>
      </ul>
    </div>
  <% end %>
  <% @user.organizers.each do |profile| %>
    <div class="card" data-id="performer<%= profile.id %>" >
      <div class="card-header">
        <%= profile.name %>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="/?profile=<%= profile.id %>&type=performer">Profil anzeigen</a></li>
        <li class="list-group-item" hidden><a href="">Profil Übertragen</a></li>
        <li class="list-group-item"><%= button_to "Profil löschen", delete_performer_url(profile.id), data: { confirm: "Sind Sie sich wirklich sicher?" }, style: "padding: 0; color: #337ab7; font-size: 14px; font-family: hero-new;", method: :delete, :remote => true %></li>
      </ul>
    </div>
  <% end %>
</div>