config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :user do
    end
  end
  
  root 'dashboard#index'
  
  get 'first_login' => 'dashboard#first_login', as: :first_login
  get 'first_event' => 'dashboard#first_event', as: :first_event
  
  get 'l/show/:id' => 'dashboard#show_location', as: :show_location
  get 'p/show/:id' => 'dashboard#show_performer', as: :show_performer
  get 'o/show/:id' => 'dashboard#show_organizer', as: :show_organizer
  
  get 'l/:id/edit_images' => 'location#edit_images'
  get 'p/:id/edit_images' => 'performer#edit_images'
  get 'e/:id/edit_images' => 'event#edit_images'
  get 'o/:id/edit_images' => 'organizer#edit_images'
  get 'o/:id/edit_profile_image' => 'organizer#edit_profile_image'
  
  get 'l/:id/events' => 'location#events'
  get 'p/:id/events' => 'performer#events'
  get 'o/:id/events' => 'organizer#events'
  
  get 'l/:id/edit_informations' => 'location#edit_informations'
  get 'p/:id/edit_informations' => 'performer#edit_informations'
  get 'o/:id/edit_informations' => 'organizer#edit_informations'
  get 'e/:id/edit' => 'event#edit'

  patch 'l/:id/edit_informations' => 'location#update_informations', as: :edit_location_informations
  patch 'p/:id/edit_informations' => 'performer#update_informations', as: :edit_performer_informations
  patch 'o/:id/edit_informations' => 'organizer#update_informations', as: :edit_organizer_informations
  patch 'e/:id/edit' => 'event#update', as: :update_event
  
  get 'l/:id/share' => 'location#share'
  get 'p/:id/share' => 'performer#share'
  get 'o/:id/share' => 'organizer#share'
  get 'e/:id/share' => 'event#share'
  
  get 'l/:id/social_links' => 'location#social_links'
  get 'p/:id/social_links' => 'performer#social_links'
  get 'o/:id/social_links' => 'organizer#social_links'
  get 'e/:id/social_links' => 'event#social_links'
  
  get 'p/:id/requests' => 'performer#requests'
  get 'o/:id/requests' => 'organizer#requests'
  
  get 'e/:id/tickets' => 'event#tickets'
  get 'e/:id/performer' => 'event#edit_performer'
  get 'e/:id/premium' => 'event#edit_premium'
  get 'e/:id/statistiken' => 'event#statistiken'
  patch 'e/:id/toggle-online' => 'event#toggle_online'
  
  
  patch 'l/:id/social_links' => 'location#edit_social_links', as: :edit_location_social_links
  patch 'p/:id/social_links' => 'performer#edit_social_links', as: :edit_performer_social_links
  patch 'o/:id/social_links' => 'organizer#edit_social_links', as: :edit_organizer_social_links
  patch 'e/:id/social_links' => 'event#update_social_links', as: :update_event_social_links
  
  get 'l/:id/opening_hours' => 'location#opening_hours'
  patch 'l/:id/opening_hours' => 'location#update_opening_hours', as: :update_opening_hours
  
  post 'l/create_from_event' => 'location#create_from_event', as: :create_location_from_event
  get 'l/search_from_event' => 'location#search_from_event'

  post 'p/create_from_event' => 'performer#create_from_event', as: :create_performer_from_event
  get 'p/search_from_event' => 'performer#search_from_event'
  post 'performer-request' => 'performer#performer_request'
  patch 'performer-request/:id' => 'performer#update_performer_request'
  delete 'delete-performer-request' => 'performer#delete_performer_request', as: :delete_performer_request
  
  post 'o/create_from_event' => 'organizer#create_from_event', as: :create_organizer_from_event
  get 'o/search_from_event' => 'organizer#search_from_event'
  post 'organizer-request' => 'organizer#organizer_request'
  patch 'organizer-request/:id' => 'organizer#update_organizer_request'
  delete 'delete-organizer-request' => 'organizer#delete_organizer_request', as: :delete_organizer_request
  
  
  get 'einstellungen' => 'dashboard#settings'
  get 'einstellungen/profiles' => 'dashboard#profiles'
  get 'einstellungen/abo' => 'dashboard#abo'
  get 'einstellungen/abo/plans' => 'payment#plans'
  get 'einstellungen/abo/bezahlen' => 'payment#payment_method'
  get 'statistiken' => 'dashboard#statistiken'
  get 'select_abo' => 'payment#select_abo', as: :select_abo
  
  get 'success' => 'payment#success'  
  get 'cancel' => 'payment#cancel'
  
  post 'webhook/customer_updated' => 'payment#customer_updated'
  post 'webhook/charge' => 'payment#charge'
  post 'webhook/invoice_created' => 'payment#invoice_created'
  
  post 'pageview' => 'page_view#create'
  
  get 'neue-location' => 'dashboard#new_location'
  get 'neuer-performer' =>'dashboard#new_performer'
  get 'neues-event' => 'dashboard#new_event'
  get 'neuer-organizer' => 'dashboard#new_organizer'
  
  get 'fertigstellen/:type/:id' => 'dashboard#fertigstellen'
  
  get 'event-bearbeiten/:id' => 'dashboard#edit_event'
  get 'performer-bearbeiten/:id' => 'dashboard#edit_performer'

  post 'event/create' => 'event#create_event1', as: :create_event1
  post 'event/:id/add_images' =>  'event#add_images'
  post 'event/select-plan/:id' => 'event#select_plan'
  patch 'event/create3/:id' =>  'event#create_event3', as: :create_event3
  
  post 'create-ticket' =>  'ticket#create', as: :create_ticket
  
  post 'create-link' =>  'social_link#create', as: :create_link
  
  post 'location/create' => 'location#create_location1', as: :create_location1
  post 'location/:id/add_images' =>  'location#add_images'
  patch 'location/create3/:id' =>  'location#create_location3', as: :create_location3
  
  post 'performer/create' => 'performer#create_performer1', as: :create_performer1
  post 'performer/:id/add_image' =>  'performer#add_image'
  
  post 'organizer/create' => 'organizer#create_organizer1', as: :create_organizer1
  post 'organizer/:id/add_image' =>  'organizer#add_image'
  post 'organizer/:id/add_profile_image' =>  'organizer#add_profile_image'
  
  post 'opening_hour/create' => 'opening_hour#create'
  post 'social_link/create' => 'social_link#create'
  post 'ticket/create' => 'ticket#create'
  
  get 'performer/search' => 'event#search_performer'
  post 'performer/invite' => 'event#invite_performer', as: :invite_performer
  post 'performer/create' => 'performer#create'
  
  get 'organizer/search' => 'event#search_organizer'
  post 'organizer/invite' => 'event#invite_organizer', as: :invite_organizer
  post 'organizer/create' => 'organizer#create'
  
  patch 'event/edit/:id' => 'event#edit', as: :edit_event
  patch 'location/edit/:id' => 'location#edit'
  patch 'opening_hour/edit/:id' => 'opening_hour#edit'
  patch 'social_link/edit/:id' => 'social_link#edit'
  patch 'ticket/edit/:id' => 'ticket#edit'
  patch 'performer/edit/:id' => 'performer#edit', as: :edit_performer
  
  delete 'event/delete/:id' => 'event#delete', as: :delete_event
  delete 'location/delete/:id' => 'location#delete', as: :delete_location
  delete 'delete_image/:id' => 'dashboard#delete_image', as: :delete_image
  delete 'opening_hour/delete/:id' => 'opening_hour#delete'
  delete 'social_link/delete/:id' => 'social_link#destroy', as: :destroy_link
  delete 'ticket/delete/:id' => 'ticket#destroy', as: :destroy_ticket
  delete 'performer/delete/:id' => 'performer#delete', as: :delete_performer
  delete 'organizer/delete/:id' => 'organizer#delete', as: :delete_organizer
  
  devise_for :users
  
  patch 'update_invoice_mail' => 'dashboard#invoice_email', as: :update_invoice_mail
  
  # Event, Location & Performer Views
  
  get 'location/:path' => 'public_view#location'
  get 'performer/:path' => 'public_view#performer'
  get 'organizer/:path' => 'public_view#organizer'
  get 'event/:path' => 'public_view#event'
  get 'event/:path/tickets' => 'public_view#tickets'
  
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
   skip_before_action :verify_authenticity_token
   layout "dashboard"
  
  def create_location1 # Name, Category, Adresse
    name = params[:locationname]
    category = params[:category]
    formatted_address = params[:formatted_address]
    route = params[:route]
    street_number = params[:street_number]
    postal_code = params[:postal_code]
    locality = params[:locality]
    # place_id = params[:place_id]
    lat = params[:lat]
    lng = params[:lng]
    
    path = (locality + " " + name).downcase.gsub(" ", "-").gsub('ö', 'oe').gsub('ä', 'ae').gsub('ü', 'ue').gsub('ß', 'ss')
    x = 0
    while !Location.find_by_path(path).nil?
      if x > 0
        path.chop!
      end
      x += 1
      path +=  x.to_s
    end
    
    @location = Location.create(user_id: current_user.id, name: name, category: category, formatted_address: formatted_address, 
                                route: route, street_number: street_number, postal_code: postal_code, locality: locality, lat: lat, lng: lng, path: path)
    
    if @location.save
      respond_to do |format|
        format.js { render partial: 'location/success1' }
      end
    else
      respond_to do |format|
        format.js { render partial: 'location/error1', resource: "Location"  }
      end
    end
    
  end
  
  def add_images # Profilbild & Bilder
    require "tinify"
    Tinify.key = "CQXQ1v8qCGY7FLND9P1mSXtqPyVdBF3r"
    if params[:id] == 0
      @location = Location.last
    else
      @location = Location.find(params[:id])
    end
    
    if current_user.max_files == @location.images.length
      respond_to do |format|
        format.js {render :status => 500}
      end
    end
    
    image = params[:file]
    
     if !@location.thumbnail.attached? 
       
      thumbnail = File.basename(image.original_filename, File.extname(image.original_filename)) + '-thumbnail' + File.extname(image.original_filename)

      source_thumbnail = Tinify.from_file(image.tempfile)
      resized_thumbnail = source_thumbnail.resize(
        method: "cover",
        width: 80,
        height: 80
      )
       resized_thumbnail.to_file('/tmp/' + thumbnail)
       @location.thumbnail.attach(io: File.open('/tmp/' + thumbnail), filename: thumbnail)
       
     end
      
        source = Tinify.from_file(image.tempfile)
        resized = source.resize(
          method: "cover",
          width: 750,
          height: 440
        )

        resized.to_file('/tmp/' + image.original_filename)

        @location.images.attach(io: File.open('/tmp/' + image.original_filename), filename: image.original_filename)
    
  end
  
  def create_location3 # Beschreibung & Öffnungszeiten
    @location = Location.find(params[:id])    
    @location.update(description: params[:description])    
    
    json = JSON.parse(params[:opening_hours])
    index = 1
    json.each do |day|
      if day["isActive"]
           OpeningHour.create(location: @location, week_day: index, start_time: day["timeFrom"], end_time: day["timeTill"])
      end
     index += 1
     if index === 7
       index = 0
     end
     end
    
    @location.save
  end

  def edit_images
    @location = Location.find(params[:id])
  end

  def edit_informations
    @location = Location.find(params[:id])
  end
  
  def update_informations
    formatted_address = params[:formatted_address]
    route = params[:route]
    street_number = params[:street_number]
    postal_code = params[:postal_code]
    locality = params[:locality]
    # place_id = params[:place_id]
    lat = params[:lat]
    lng = params[:lng]
    
    @location = Location.find(params[:id])
    @location.update(name: params[:location][:name], description: params[:location][:description], category: params[:location][:category], 
                     formatted_address: formatted_address, route: route, street_number: street_number, postal_code: postal_code, locality: locality, lat: lat, lng: lng)
    @location.save
    
    path = '/?profile=' + @location.id.to_s + '&type=location'
    
    redirect_to path
  end
  
  def opening_hours 
    @location = Location.find(params[:id])
    @opening_hours = @location.opening_hours
    @special_hours = OpeningHour.new()
    
  end
  
  def update_opening_hours
    @location = Location.find(params[:id])
    if params[:opening_hours] != ''
      
      json = JSON.parse(params[:opening_hours])
      index = 1
      json.each do |day|
        wday = @location.opening_hours.find_by_week_day(index)
        if wday.nil? && day["isActive"]
           OpeningHour.create(location: @location, week_day: index, start_time: day["timeFrom"], end_time: day["timeTill"])
        elsif !wday.nil? && day["isActive"]
          wday.update(start_time: day["timeFrom"], end_time: day["timeTill"])
        elsif !wday.nil? && !day["isActive"]
          wday.delete!
        end
         index += 1 
         if index === 7
           index = 0
         end
       end
    end
      
    path = '/?profile=' + @location.id.to_s + '&type=location'
    
    redirect_to path
    
  end
  
  def share
    @location = Location.find(params[:id])
  end
  
  def events
    @location = Location.find(params[:id])
    @own_events = @location.own_events
  end
  
  def social_links
    @location = Location.find(params[:id])
    @social_links = @location.social_links
  end
  
  def edit_social_links
    @location = Location.find(params[:id])
    @facebook = @location.social_links.find_by_channel('Facebook')
    @instagram = @location.social_links.find_by_channel('Instagram')
    @youtube = @location.social_links.find_by_channel('YouTube')
    @soundcloud = @location.social_links.find_by_channel('SoundCloud')
    @webseite = @location.social_links.find_by_channel('Webseite')
    
    if @facebook.nil? && params[:facebook] != ""
      SocialLink.create(channel: 'Facebook', url: params[:facebook], location_id: @location.id)
    elsif !@facebook.nil? && params[:facebook] != ""
      @facebook.update(url: params[:facebook])
    elsif !@facebook.nil? && params[:facebook] == ""
      @facebook.delete
    end
    
    if @instagram.nil? && params[:instagram] != ""
      SocialLink.create(channel: 'Instagram', url: params[:instagram], location_id: @location.id)
    elsif !@instagram.nil? && params[:instagram] != ""
      @instagram.update(url: params[:instagram])
    elsif !@instagram.nil? && params[:instagram] == ""
      @instagram.delete
    end
    
    if @youtube.nil? && params[:youtube] != ""
      SocialLink.create(channel: 'YouTube', url: params[:youtube], location_id: @location.id)
    elsif !@youtube.nil? && params[:youtube] != ""
      @youtube.update(url: params[:youtube])
    elsif !@youtube.nil? && params[:youtube] == ""
      @youtube.delete
    end
    
    if @soundcloud.nil? && params[:soundcloud] != ""
      SocialLink.create(channel: 'SoundCloud', url: params[:soundcloud], location_id: @location.id)
    elsif !@soundcloud.nil? && params[:soundcloud] != ""
      @soundcloud.update(url: params[:soundcloud])
    elsif !@soundcloud.nil? && params[:soundcloud] == ""
      @soundcloud.delete
    end
    
    if @webseite.nil? && params[:webseite] != ""
      SocialLink.create(channel: 'Webseite', url: params[:webseite], location_id: @location.id)
    elsif !@webseite.nil? && params[:webseite] != ""
      @webseite.update(url: params[:webseite])
    elsif !@webseite.nil? && params[:webseite] == ""
      @webseite.delete
    end
    
    path = '/?profile=' + @location.id.to_s + '&type=location'
    
    redirect_to path
    
  end
  
  def create_from_event
    name = params[:locationname]
    category = params[:category]
    formatted_address = params[:formatted_address]
    route = params[:route]
    street_number = params[:street_number]
    postal_code = params[:postal_code]
    locality = params[:locality]
    # place_id = params[:place_id]
    lat = params[:lat]
    lng = params[:lng]
    
    path = (locality + " " + name).downcase.gsub(" ", "-").gsub('ö', 'oe').gsub('ä', 'ae').gsub('ü', 'ue').gsub('ß', 'ss')
    x = 0
    while !Location.find_by_path(path).nil?
      if x > 0
        path.chop!
      end
      x += 1
      path +=  x.to_s
    end
    
    @location = Location.create(name: name, category: category, formatted_address: formatted_address, 
                                route: route, street_number: street_number, postal_code: postal_code, locality: locality, lat: lat, lng: lng, path: path)
    
    if @location.save
      respond_to do |format|
        format.js { render partial: 'location/success_from_event' }
      end
    else
      respond_to do |format|
        format.js { render partial: 'location/error_from_event', resource: "Location"  }
      end
    end
    
  end
  
  def search_from_event
    search = params[:location_search].split(' ')
    first_search = search.shift
    all_locations = Array.new(0)
    all_locations << Location.where('LOWER(name) LIKE ?', "%#{first_search.downcase}%").limit(10)
    all_locations << Location.where('LOWER(locality) LIKE ?', "%#{first_search.downcase}%").limit(10)
    all_locations.flatten!
    
    if search.length > 0  
      search.each do |str|
        @locations = all_locations.select { |s| s[:locality].downcase.include?(str.downcase) || s[:name].downcase.include?(str.downcase) }
      end
    else
      @locations = all_locations
    end
    respond_to do |format|
      format.js { render partial: 'location/search' }
    end
  end
  
  
  def delete
    @profile = Location.find(params[:id])
    @profile.delete
    
    respond_to do |format|
      format.js { render partial: 'location/destroyed' }
    end
  end
  
  private
  
  
end

app/helpers/location_helper.rb
module LocationHelper
end

app/views/location/_search.html.erb
<div style="max-height: 160px; overflow: scroll;">
<% @locations.each do |resource| %>
  <a onclick="selectLocation(<%= resource.id %>, '<%= resource.name %>')" class="search-result">
    <img src="<% if resource.thumbnail.attached? %><%= url_for(resource.thumbnail) %><% else %>/images/blurred-image-2.jpg<% end %>" alt="" class="search-result-img">
    <div>
      <h2><%= resource.name %></h2>
      <span class="subheader"><%= resource.category %>, <%= resource.locality %></span>
    </div>
  </a>
<% end %>
</div>
<a onclick="newLocation()" id="newLocationButton">Neu erstellen</a>

app/views/location/_search.js.erb
$('#location-search-preview').addClass('active');
$('#location-search-preview').html("<%= j(render 'location/search.html') %>");

app/views/location/_success1.js.erb
var accordion1 = $('#accordion1');
var accordion2 = $('#accordion2');
var accordion3 = $('#accordion3');

var form3 = $('#form3');
var button1 = $('#button1');
var button2 = $('#button2');
var button4 = $('#button4');

accordion1.removeClass('active').addClass('done');
accordion2.addClass('active');

button1.remove();
button2.css('display', 'block');

location_id = <%= @location.id %>;

form3.attr('action', '/location/create3/' + <%= @location.id %>);

location_id = <%= @location.id %>;


var businessHoursManager = $("#business-hours").businessHours({
    postInit:function(){
        $('.operationTimeFrom, .operationTimeTill').timepicker({
            'timeFormat': 'H:i',
            'step': 15
            });
        $('.operationTimeFrom, .operationTimeTill, .operationState').on('change', function(){
          $("textarea#opening_hours").val(JSON.stringify(businessHoursManager.serialize()));
        });
    },
    dayTmpl:'<div class="dayContainer" >' +
        '<div data-original-title="" class="colorBox"><input type="checkbox" class="invisible operationState"></div>' +
        '<div class="weekday"></div>' +
        '<div class="operationDayTimeContainer">' +
        '<div class="operationTime input-group"><input type="text" name="startTime" class="form-control operationTimeFrom" value=""></div>' +
        '<div class="operationTime input-group"><input type="text" name="endTime" class="form-control operationTimeTill" value=""></div>' +
        '</div></div>'
});

app/views/location/edit_informations.html.erb
<%= render 'dashboard/shared/header2', header: 'Generelle Informationen', link: @location.id, type: 'location' %>
<div class="container">
  <%= form_for(@location, :html => {role: "form", id: "form1"}, url: edit_location_informations_url(@location.id)) do |f| %>
    <div class="form-group">
      <label for="name">Name</label>
      <%= f.text_field :name, placeholder: 'Name', class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="category">Kategorie</label>
      <%= f.select(:category, Location.categories, {}, {class: "form-control"}) %>
    </div>
    <div class="form-group">
      <label for="address-lookup">Adresse</label>
      <input type="text" class="form-control is-valid" id="address-lookup" value="<%= @location.formatted_address %>" aria-describedby="addressHelp" placeholder="Adresse">
      <small id="addressHelp" class="form-text text-muted">Geben Sie Ihre Adresse ein und klicken Sie auf die genaue Adresse im Dropdown</small>
      <div style="display: none">
        Latitude:   <input name="lat" type="text" value="<%= @location.lat %>">
        Longitude:  <input name="lng" type="text" value="<%= @location.lng %>">
        Address:    <input name="formatted_address" type="text" value="<%= @location.formatted_address %>">
        Locality:   <input name="locality" type="text" value="<%= @location.locality %>">
        Street:     <input name="route" type="text" value="<%= @location.route %>">
        Streetnr:   <input name="street_number" type="text" id="street_number" value="<%= @location.street_number %>">
        PLZ:        <input name="postal_code" type="text" value="<%= @location.postal_code %>">
      </div>
    </div>
    <div class="form-group">
      <label for="description">Beschreibung</label>
      <%= f.text_area(:description, rows: 5, class: 'form-control') %>
    </div>
  <% end %>
  
</div>
<div class="footer">
  <a href='' class="footer-link" id="button1">Aktualisieren</a>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBNAXfMrJDNWqcq8bW6OhWgZd6XUi-F1UI&libraries=places"></script>
<script src="/jquery.geocomplete.min.js"></script>
<script>
  $('#address-lookup').geocomplete({ details: "form" }).bind("geocode:result", function(event, result){
    console.log(result);
    if($('#street_number').val() !== "") {
      $('#address-lookup').removeClass('is-invalid');
      $('#address-lookup').addClass('is-valid');
      console.log($('#street_number').val());
    } else {
      $('#address-lookup').removeClass('is-valid');
      $('#address-lookup').addClass('is-invalid');
      console.log($('#street_number').val());
    };
  });
</script>
<script>
  $('#button1').on('click', function(){
    $('#form1').submit();
  });
</script>

app/views/location/opening_hours.html.erb
<%= render 'dashboard/shared/header2', header: 'Öffnungszeiten bearbeiten', link: @location.id, type: 'location' %>
<div class="container">
  <%= form_for(@location, :html => {role: "form", id: "form1"}, url: update_opening_hours_url(@location.id)) do |f| %>
      <textarea type="text" name="opening_hours" id="opening_hours" hidden></textarea>
  <% end %>
  <div class="form-group" id="business-hours"></div>
</div>
<div class="footer">
  <a href='' class="footer-link" id="button1">Aktualisieren</a> 
</div>
  <!-- JQuery Business Hours -->
  <script src="https://jonthornton.github.io/jquery-timepicker/jquery.timepicker.js"></script>
  <script src="/jquery.businessHours.min.js"></script>
  <script>
    var businessHoursManager = $("#business-hours").businessHours({
        postInit:function(){
            $('.operationTimeFrom, .operationTimeTill').timepicker({
                'timeFormat': 'H:i',
                'step': 15
                });
            $('.operationTimeFrom, .operationTimeTill, .operationState').on('change', function(){
              $("textarea#opening_hours").val(JSON.stringify(businessHoursManager.serialize()));
            });
        },
        dayTmpl:'<div class="dayContainer" >' +
            '<div data-original-title="" class="colorBox"><input type="checkbox" class="invisible operationState"></div>' +
            '<div class="weekday"></div>' +
            '<div class="operationDayTimeContainer">' +
            '<div class="operationTime input-group"><input type="text" name="startTime" class="form-control operationTimeFrom" value=""></div>' +
            '<div class="operationTime input-group"><input type="text" name="endTime" class="form-control operationTimeTill" value=""></div>' +
            '</div></div>',
      operationTime: <%= @location.open_json.html_safe %>
    });
  </script>
  <script>
  $('#button1').on('click', function(){
    $('#form1').submit();
  });
</script>

app/views/location/social_links.html.erb
<%= render 'dashboard/shared/header2', header: 'Social Links', link: @location.id, type: 'location' %>
<div class="container">
  <%= form_for(@location, :html => {role: "form", id: "form1"}, url: edit_location_social_links_url(@location.id)) do |f| %>
  <!-- Facebook Page -->
    <div class="form-group mb-3">
      <label for="facebook">Facebook Page</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1"><img src="/images/facebook.svg" alt="Facebook" width="20px"></span>
        </div>
        <input type="text" placeholder="Link" aria-label="facebook" aria-describedby="basic-addon1" name="facebook" id="facebook" class="form-control
        <% if !@social_links.find_by_channel('Facebook').nil? %>is-valid " value="<%= @social_links.find_by_channel('Facebook').url %><% end %>">
      </div>
      <small id="basic-addon1" class="form-text text-muted">Die passende Facebook Gruppe.</small>
    </div>

  <!-- Instagram -->

    <div class="form-group mb-3">
      <label for="instagram">Instagram Akkount</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon2"><img src="/images/instagram.svg" alt="Instagram" width="20px"></span>
      </div>
      <input type="text" placeholder="Username" aria-label="instagram" id="instagram" aria-describedby="basic-addon2" name="instagram" class="form-control
      <% if !@social_links.find_by_channel('Instagram').nil? %>is-valid" value="<%= @social_links.find_by_channel('Instagram').url %><% end %>">
    </div>
    </div>

  <!-- YouTube Video -->
    <div class="form-group mb-3">
      <label for="youtube">YouTube Video</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon3"><img src="/images/youtube.svg" alt="YouTube" width="20px"></span>
        </div>
        <input type="text" placeholder="Videolink" aria-label="youtube" id="youtube" aria-describedby="basic-addon3" name="youtube" class="form-control
        <% if !@social_links.find_by_channel('YouTube').nil? %>is-valid" value="<%= @social_links.find_by_channel('YouTube').url %><% end %> ">    
      </div>
    </div>

  <!-- SoundCloud -->
    <div class="form-group mb-3">
      <label for="soundcloud">SoundCloud Link</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon4"><img src="/images/soundcloud.svg" alt="Soundcloud" width="20px"></span>
        </div>
        <input type="text" placeholder="http://www.soundcloud.com/username" aria-label="soundcloud" id="soundcloud" aria-describedby="basic-addon4" name="soundcloud" class="form-control
        <% if !@social_links.find_by_channel('SoundCloud').nil? %>is-valid" value="<%= @social_links.find_by_channel('SoundCloud').url %><% end %>">
      </div>
    </div>

  <!-- Webseite -->
    <div class="form-group mb-3">
      <label for="webseite">Webseite</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon4"><img src="/images/website.svg" alt="Website" width="20px"></span>
        </div>
        <input type="text" placeholder="www.beispiel.de" aria-label="webseite" id="webseite" aria-describedby="basic-addon4" name="webseite" class="form-control
        <% if !@social_links.find_by_channel('Webseite').nil? %>is-valid" value="<%= @social_links.find_by_channel('Webseite').url %><% end %>">
      </div>
    </div>
  
  <% end %>
</div>
<div class="footer">
  <a href='' class="footer-link" id="button1">Aktualisieren</a> 
</div>
<script>
  $('#button1').on('click', function(){
    $('#form1').submit();
  });
</script>