config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :user do
    end
  end
  
  root 'dashboard#index'
  
  get 'first_login' => 'dashboard#first_login', as: :first_login
  get 'first_event' => 'dashboard#first_event', as: :first_event
  
  get 'l/show/:id' => 'dashboard#show_location', as: :show_location
  get 'p/show/:id' => 'dashboard#show_performer', as: :show_performer
  get 'o/show/:id' => 'dashboard#show_organizer', as: :show_organizer
  
  get 'l/:id/edit_images' => 'location#edit_images'
  get 'p/:id/edit_images' => 'performer#edit_images'
  get 'e/:id/edit_images' => 'event#edit_images'
  get 'o/:id/edit_images' => 'organizer#edit_images'
  get 'o/:id/edit_profile_image' => 'organizer#edit_profile_image'
  
  get 'l/:id/events' => 'location#events'
  get 'p/:id/events' => 'performer#events'
  get 'o/:id/events' => 'organizer#events'
  
  get 'l/:id/edit_informations' => 'location#edit_informations'
  get 'p/:id/edit_informations' => 'performer#edit_informations'
  get 'o/:id/edit_informations' => 'organizer#edit_informations'
  get 'e/:id/edit' => 'event#edit'

  patch 'l/:id/edit_informations' => 'location#update_informations', as: :edit_location_informations
  patch 'p/:id/edit_informations' => 'performer#update_informations', as: :edit_performer_informations
  patch 'o/:id/edit_informations' => 'organizer#update_informations', as: :edit_organizer_informations
  patch 'e/:id/edit' => 'event#update', as: :update_event
  
  get 'l/:id/share' => 'location#share'
  get 'p/:id/share' => 'performer#share'
  get 'o/:id/share' => 'organizer#share'
  get 'e/:id/share' => 'event#share'
  
  get 'l/:id/social_links' => 'location#social_links'
  get 'p/:id/social_links' => 'performer#social_links'
  get 'o/:id/social_links' => 'organizer#social_links'
  get 'e/:id/social_links' => 'event#social_links'
  
  get 'p/:id/requests' => 'performer#requests'
  get 'o/:id/requests' => 'organizer#requests'
  
  get 'e/:id/tickets' => 'event#tickets'
  get 'e/:id/performer' => 'event#edit_performer'
  get 'e/:id/premium' => 'event#edit_premium'
  get 'e/:id/statistiken' => 'event#statistiken'
  patch 'e/:id/toggle-online' => 'event#toggle_online'
  
  
  patch 'l/:id/social_links' => 'location#edit_social_links', as: :edit_location_social_links
  patch 'p/:id/social_links' => 'performer#edit_social_links', as: :edit_performer_social_links
  patch 'o/:id/social_links' => 'organizer#edit_social_links', as: :edit_organizer_social_links
  patch 'e/:id/social_links' => 'event#update_social_links', as: :update_event_social_links
  
  get 'l/:id/opening_hours' => 'location#opening_hours'
  patch 'l/:id/opening_hours' => 'location#update_opening_hours', as: :update_opening_hours
  
  post 'l/create_from_event' => 'location#create_from_event', as: :create_location_from_event
  get 'l/search_from_event' => 'location#search_from_event'

  post 'p/create_from_event' => 'performer#create_from_event', as: :create_performer_from_event
  get 'p/search_from_event' => 'performer#search_from_event'
  post 'performer-request' => 'performer#performer_request'
  patch 'performer-request/:id' => 'performer#update_performer_request'
  delete 'delete-performer-request' => 'performer#delete_performer_request', as: :delete_performer_request
  
  post 'o/create_from_event' => 'organizer#create_from_event', as: :create_organizer_from_event
  get 'o/search_from_event' => 'organizer#search_from_event'
  post 'organizer-request' => 'organizer#organizer_request'
  patch 'organizer-request/:id' => 'organizer#update_organizer_request'
  delete 'delete-organizer-request' => 'organizer#delete_organizer_request', as: :delete_organizer_request
  
  
  get 'einstellungen' => 'dashboard#settings'
  get 'einstellungen/profiles' => 'dashboard#profiles'
  get 'einstellungen/abo' => 'dashboard#abo'
  get 'einstellungen/abo/plans' => 'payment#plans'
  get 'einstellungen/abo/bezahlen' => 'payment#payment_method'
  get 'statistiken' => 'dashboard#statistiken'
  get 'select_abo' => 'payment#select_abo', as: :select_abo
  
  get 'success' => 'payment#success'  
  get 'cancel' => 'payment#cancel'
  
  post 'webhook/customer_updated' => 'payment#customer_updated'
  post 'webhook/charge' => 'payment#charge'
  post 'webhook/invoice_created' => 'payment#invoice_created'
  
  post 'pageview' => 'page_view#create'
  
  get 'neue-location' => 'dashboard#new_location'
  get 'neuer-performer' =>'dashboard#new_performer'
  get 'neues-event' => 'dashboard#new_event'
  get 'neuer-organizer' => 'dashboard#new_organizer'
  
  get 'fertigstellen/:type/:id' => 'dashboard#fertigstellen'
  
  get 'event-bearbeiten/:id' => 'dashboard#edit_event'
  get 'performer-bearbeiten/:id' => 'dashboard#edit_performer'

  post 'event/create' => 'event#create_event1', as: :create_event1
  post 'event/:id/add_images' =>  'event#add_images'
  post 'event/select-plan/:id' => 'event#select_plan'
  patch 'event/create3/:id' =>  'event#create_event3', as: :create_event3
  
  post 'create-ticket' =>  'ticket#create', as: :create_ticket
  
  post 'create-link' =>  'social_link#create', as: :create_link
  
  post 'location/create' => 'location#create_location1', as: :create_location1
  post 'location/:id/add_images' =>  'location#add_images'
  patch 'location/create3/:id' =>  'location#create_location3', as: :create_location3
  
  post 'performer/create' => 'performer#create_performer1', as: :create_performer1
  post 'performer/:id/add_image' =>  'performer#add_image'
  
  post 'organizer/create' => 'organizer#create_organizer1', as: :create_organizer1
  post 'organizer/:id/add_image' =>  'organizer#add_image'
  post 'organizer/:id/add_profile_image' =>  'organizer#add_profile_image'
  
  post 'opening_hour/create' => 'opening_hour#create'
  post 'social_link/create' => 'social_link#create'
  post 'ticket/create' => 'ticket#create'
  
  get 'performer/search' => 'event#search_performer'
  post 'performer/invite' => 'event#invite_performer', as: :invite_performer
  post 'performer/create' => 'performer#create'
  
  get 'organizer/search' => 'event#search_organizer'
  post 'organizer/invite' => 'event#invite_organizer', as: :invite_organizer
  post 'organizer/create' => 'organizer#create'
  
  patch 'event/edit/:id' => 'event#edit', as: :edit_event
  patch 'location/edit/:id' => 'location#edit'
  patch 'opening_hour/edit/:id' => 'opening_hour#edit'
  patch 'social_link/edit/:id' => 'social_link#edit'
  patch 'ticket/edit/:id' => 'ticket#edit'
  patch 'performer/edit/:id' => 'performer#edit', as: :edit_performer
  
  delete 'event/delete/:id' => 'event#delete', as: :delete_event
  delete 'location/delete/:id' => 'location#delete', as: :delete_location
  delete 'delete_image/:id' => 'dashboard#delete_image', as: :delete_image
  delete 'opening_hour/delete/:id' => 'opening_hour#delete'
  delete 'social_link/delete/:id' => 'social_link#destroy', as: :destroy_link
  delete 'ticket/delete/:id' => 'ticket#destroy', as: :destroy_ticket
  delete 'performer/delete/:id' => 'performer#delete', as: :delete_performer
  delete 'organizer/delete/:id' => 'organizer#delete', as: :delete_organizer
  
  devise_for :users
  
  patch 'update_invoice_mail' => 'dashboard#invoice_email', as: :update_invoice_mail
  
  # Event, Location & Performer Views
  
  get 'location/:path' => 'public_view#location'
  get 'performer/:path' => 'public_view#performer'
  get 'organizer/:path' => 'public_view#organizer'
  get 'event/:path' => 'public_view#event'
  get 'event/:path/tickets' => 'public_view#tickets'
  
end

app/models/performer.rb
class Performer < ApplicationRecord
  has_one :user
  has_many :social_links, :dependent => :delete_all
  has_many :performer_requests
  has_many :events, -> { where performer_requests: { accepted: true } } ,
           :through => :performer_requests, 
           :class_name => "Event", 
           :source => :event
  
  has_one_attached :profile_image
  has_one_attached :profile_image_thumbnail
  
  def own_events
    user = User.find(self.user_id)    
    self.events.where('user_id = ?', user.id)
  end
  
  def upcoming_events
    self.events.where('start_time > ?', Time.now).order('start_time ASC')
  end
  
  def finished_events
    self.events.where('start_time < ?', Time.now)
  end
  
  def self.categories
    arr = ['', 'DJ', 'Band', 'Sänger', 'Unterhalter', 'Künstler', 'Tanzgruppe']
    return arr
  end
  
  def category_schema
    return self.category
  end
  
  def url 
    return '/performer/' + self.path
  end
  
  def user
    if self.user_id.nil?
      return nil
    else
      User.find(self.user_id)
    end
  end
  
  def images
    arr = []
    arr << self.profile_image
  end
  
  def path_str
    path = self.name.downcase.gsub(" ", "-")
    x = 0
    while !Performer.find_by_path(path).nil?
      if x > 0
        path.chop!
      end
      x += 1
      path +=  x.to_s
    end
    return path
  end
  
  def page_views
    PageView.where('path = ?', '/performer/' + self.path)
  end
  
  def uniq_sessions
    PageView.where('path = ?', '/performer/' + self.path).map { |x| x.session_id }.uniq.length
  end
  
end

app/controllers/performer_controller.rb
class PerformerController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout 'dashboard'
  
  def create_performer1 # Name, Category, Start & Endtime
    name = params[:performername]
    
    path = name.downcase.gsub(" ", "-").gsub('ö', 'oe').gsub('ä', 'ae').gsub('ü', 'ue').gsub('ß', 'ss')
    x = 0
    while !Performer.find_by_path(path).nil?
      if x > 0
        path.chop!
      end
      x += 1
      path +=  x.to_s
    end
    
    @performer = Performer.new(user_id: current_user.id, name: params[:performername], category: params[:performer][:category], description: params[:description], path: path)

    @performer.save
    respond_to do |format|
      format.js { render partial: 'performer/success1' }
    end
    
  end
  
  def add_image # Bilder
    require "tinify"
    Tinify.key = "CQXQ1v8qCGY7FLND9P1mSXtqPyVdBF3r"
    if params[:id] == 0
      @performer = Performer.last
    else
      @performer = Performer.find(params[:id])
    end
    
    image = params[:file]
       
      thumbnail = File.basename(image.original_filename, File.extname(image.original_filename)) + '-thumbnail' + File.extname(image.original_filename)

      source_thumbnail = Tinify.from_file(image.tempfile)
      resized_thumbnail = source_thumbnail.resize(
        method: "cover",
        width: 80,
        height: 80
      )
       resized_thumbnail.to_file('/tmp/' + thumbnail)
       @performer.profile_image_thumbnail.attach(io: File.open('/tmp/' + thumbnail), filename: thumbnail)

        source = Tinify.from_file(image.tempfile)
        resized = source.resize(
          method: "cover",
          width: 400,
          height: 400
        )

        resized.to_file('/tmp/' + image.original_filename)

        @performer.profile_image.attach(io: File.open('/tmp/' + image.original_filename), filename: image.original_filename)

  end

  def edit_images
    @performer = Performer.find(params[:id])
  end
  
  def edit_informations
    @performer = Performer.find(params[:id])
  end
  
  def update_informations
    @performer = Performer.find(params[:id])
    @performer.update(name: params[:performer][:name], category: params[:performer][:category], description: params[:performer][:description])
    
    @performer.save
    
    path = '/?profile=' + @performer.id.to_s + '&type=performer'
    
    redirect_to path
  end
  
  def events
    @performer = Performer.find(params[:id])
    @own_events = @performer.own_events
  end
  
  def share
    @resource = Performer.find(params[:id])
  end
  
  def social_links
    @performer = Performer.find(params[:id])
    @social_links = @performer.social_links
  end
  
  def requests
    @performer = Performer.find(params[:id])
    @requests = @performer.performer_requests
    @new_requests = @requests.where('created_at = updated_at').where(accepted: false)
    @accepted_requests = @requests.where(accepted: true)
  end
  
  def edit_social_links
    @performer = Performer.find(params[:id])
    @facebook = @performer.social_links.find_by_channel('Facebook')
    @instagram = @performer.social_links.find_by_channel('Instagram')
    @youtube = @performer.social_links.find_by_channel('YouTube')
    @soundcloud = @performer.social_links.find_by_channel('SoundCloud')
    @webseite = @performer.social_links.find_by_channel('Webseite')
    
    if @facebook.nil? && params[:facebook] != ""
      SocialLink.create(channel: 'Facebook', url: params[:facebook], performer_id: @performer.id)
    elsif !@facebook.nil? && params[:facebook] != ""
      @facebook.update(url: params[:facebook])
    elsif !@facebook.nil? && params[:facebook] == ""
      @facebook.delete
    end
    
    if @instagram.nil? && params[:instagram] != ""
      SocialLink.create(channel: 'Instagram', url: params[:instagram], performer_id: @performer.id)
    elsif !@instagram.nil? && params[:instagram] != ""
      @instagram.update(url: params[:instagram])
    elsif !@instagram.nil? && params[:instagram] == ""
      @instagram.delete
    end
    
    if @youtube.nil? && params[:youtube] != ""
      SocialLink.create(channel: 'YouTube', url: params[:youtube], performer_id: @performer.id)
    elsif !@youtube.nil? && params[:youtube] != ""
      @youtube.update(url: params[:youtube])
    elsif !@youtube.nil? && params[:youtube] == ""
      @youtube.delete
    end
    
    if @soundcloud.nil? && params[:soundcloud] != ""
      SocialLink.create(channel: 'SoundCloud', url: params[:soundcloud], performer_id: @performer.id)
    elsif !@soundcloud.nil? && params[:soundcloud] != ""
      @soundcloud.update(url: params[:soundcloud])
    elsif !@soundcloud.nil? && params[:soundcloud] == ""
      @soundcloud.delete
    end
    
    if @webseite.nil? && params[:webseite] != ""
      SocialLink.create(channel: 'Webseite', url: params[:webseite], performer_id: @performer.id)
    elsif !@webseite.nil? && params[:webseite] != ""
      @webseite.update(url: params[:webseite])
    elsif !@webseite.nil? && params[:webseite] == ""
      @webseite.delete
    end
    
    path = '/?profile=' + @performer.id.to_s + '&type=performer'
    
    redirect_to path
    
  end
  
  def create_from_event
    name = params[:performername]
    event = params[:event]
    
    path = name.downcase.gsub(" ", "-").gsub('ö', 'oe').gsub('ä', 'ae').gsub('ü', 'ue').gsub('ß', 'ss')
    x = 0
    while !Performer.find_by_path(path).nil?
      if x > 0
        path.chop!
      end
      x += 1
      path +=  x.to_s
    end
    
    @performer = Performer.new(name: params[:performername], category: params[:performercategory], path: path)

    if @performer.save     
      if @performer_request = PerformerRequest.create(performer_id: @performer.id, event_id: event)
        respond_to do |format|
          format.js { render partial: 'performer/success_from_event' }
        end
      end
    end
  end
  
  def performer_request
    @event = params[:event_id].to_i
    performer = params[:performer_id].to_i
    
    @performer = Performer.find(performer)
    
    @performer_request = PerformerRequest.new(performer_id: performer, event_id: @event)
    if @performer_request.save
      respond_to do |format|
         format.js { render partial: 'performer/request_success' }
       end
    end
  end
  
  def search_from_event
    @event = params[:event]
    search = params[:performer_search]
    @performers = Performer.where('LOWER(name) LIKE ?', "%#{search.downcase}%").limit(10)

    respond_to do |format|
      format.js { render partial: 'performer/search' }
    end
  end
  
  def update_performer_request
    if params[:accepted] == "true"
      PerformerRequest.find(params[:id]).update(accepted: true)    
    else 
      PerformerRequest.find(params[:id]).update(accepted: false) 
    end
  end
  
  def delete_performer_request
    @event = params[:event_id].to_i
    performer_request_id = params[:performer_request_id].to_i
    
    PerformerRequest.find(performer_request_id).delete
    
  end
  
  
   def delete
    @profile = Performer.find(params[:id])
    @profile.delete
    
    respond_to do |format|
      format.js { render partial: 'performer/destroyed' }
    end
  end
end

app/helpers/performer_helper.rb
module PerformerHelper
end

app/views/performer/_destroyed.js.erb
$('[data-id="performer<%= @profile.id %>"]').remove();

app/views/performer/_request_success.js.erb
$('#performer-form-group').append("<%= j(render 'performer/request_success.html') %>");

app/views/performer/edit_images.html.erb
<%= render 'dashboard/shared/header2', header: 'Bilder bearbeiten', link: @performer.id, type: 'performer' %>
<div class="editdropzone"> 
  <div class="dropzone" id="myDropzone"></div>
</div>
<% if @performer.profile_image.attached? %>
  <div class="edit-image-container" style="width: 100vw;" data-id="<%= @performer.profile_image.id %>">
    <img src="<%= url_for(@performer.profile_image) %>" alt="" width="100%">
    <%= button_to "Löschen", delete_image_url(:id => @performer.profile_image.id), method: :delete, data: { confirm: 'Sind sie sich sicher?'}, :remote => true %>
  </div>
<% end %>
<div id="image-upload">  
  <svg width="32px" height="28px" viewBox="0 0 32 28" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <g id="Page-2" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <g id="Dashboard" transform="translate(-213.000000, -463.000000)" fill="#FFFFFF" fill-rule="nonzero">
              <g id="iconfinder_image_add_103590" transform="translate(213.000000, 459.000000)">
                  <g id="image_x5F_add" transform="translate(0.000000, 4.000000)">
                      <path d="M28,4 L24,4 L20,0 L11.999,0 L8,4 L4,4 C4,4 0,4 0,8 L0,20 C0,24 4,24 4,24 C4,24 9.662,24 15.518,24 C17.132,26.411 19.879,27.999 23,28 C26.875,27.998 30.167,25.546 31.436,22.112 C31.995,21.076 32,20 32,20 C32,20 32,12 32,8 C32,4 28,4 28,4 Z M14.033,19.66 C11.686,18.847 10,16.626 10,14 C10,10.688 12.684,8 16,8 C17.914,8 19.607,8.908 20.706,10.306 C16.848,11.321 14,14.822 14,19 C14,19.223 14.018,19.441 14.033,19.66 Z M23,25.883 C19.199,25.874 16.124,22.799 16.115,19 C16.124,15.199 19.199,12.124 23,12.115 C26.799,12.124 29.874,15.199 29.883,19 C29.874,22.799 26.799,25.874 23,25.883 Z" id="Shape"></path>
                      <polygon id="Path" points="28 18 24.002 18 24.002 14 22 14 22 18 18 18 18 20 22 20 22 24 24.002 24 24.002 20 28 20"></polygon>
                  </g>
              </g>
          </g>
      </g>
  </svg>
</div>
<!-- Dropzone JS -->
<script src="https://unpkg.com/dropzone"></script>
<script src="https://unpkg.com/cropperjs"></script>
<script>
  $("#myDropzone").dropzone({ 
    url: '/performer/<%= @performer.id %>/add_image',
    maxFiles: <%= current_user.max_files %>,
    transformFile: function(file, done) {
    // Create Dropzone reference for use in confirm button click handler
    var myDropZone = this;
    // Create the image editor overlay
    var editor = document.createElement('div');
    editor.style.position = 'fixed';
    editor.style.left = 0;
    editor.style.right = 0;
    editor.style.top = 0;
    editor.style.bottom = 0;
    editor.style.zIndex = 9999;
    editor.style.backgroundColor = '#000';
    document.body.appendChild(editor);
    // Create confirm button at the top left of the viewport
    var buttonConfirm = document.createElement('button');
    buttonConfirm.className = 'btn btn-primary';
    buttonConfirm.style.position = 'absolute';
    buttonConfirm.style.right = '10px';
    buttonConfirm.style.top = '10px';
    buttonConfirm.style.zIndex = 9999;
    buttonConfirm.textContent = 'Confirm';
    editor.appendChild(buttonConfirm);
    buttonConfirm.addEventListener('click', function() {
      // Get the canvas with image data from Cropper.js
      var canvas = cropper.getCroppedCanvas({
        maxWidth: 1500,
        maxHeight: 880
      });
      // Turn the canvas into a Blob (file object without a name)
      canvas.toBlob(function(blob) {
        // Create a new Dropzone file thumbnail
        myDropZone.createThumbnail(
          blob,
          myDropZone.options.thumbnailWidth,
          myDropZone.options.thumbnailHeight,
          myDropZone.options.thumbnailMethod,
          false, 
          function(dataURL) {

            // Update the Dropzone file thumbnail
            myDropZone.emit('thumbnail', file, dataURL);
            // Return the file to Dropzone
            done(blob);
        });
      });
      // Remove the editor from the view
      document.body.removeChild(editor);
    });
    // Create an image node for Cropper.js
    var image = new Image();
    image.src = URL.createObjectURL(file);
    editor.appendChild(image);

    // Create Cropper.js
    var cropper = new Cropper(image, { aspectRatio: 1 });
  }});

$('.dz-default').html('Dateien nach hier ziehen oder klicken zum hochladen');  
</script>
<script>
 $('#image-upload').on ('click',function(){
   $('.editdropzone').toggleClass('active')
 });
</script>

app/views/performer/edit_informations.html.erb
<%= render 'dashboard/shared/header2', header: 'Generelle Informationen', link: @performer.id, type: 'performer' %>
<div class="container">
  <%= form_for(@performer, :html => {role: "form", id: "form1"}, url: edit_performer_informations_url(@performer.id)) do |f| %>
    <div class="form-group">
      <label for="name">Name</label>
      <%= f.text_field :name, placeholder: 'Name', class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="category">Kategorie</label>
      <%= f.select(:category, Performer.categories, {}, {class: "form-control"}) %>
    </div>
    <div class="form-group">
      <label for="description">Beschreibung</label>
      <%= f.text_area(:description, rows: 5, class: 'form-control') %>
    </div>
  <% end %>
</div>
<div class="footer">
  <a href='' class="footer-link" id="button1">Aktualisieren</a> 
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBNAXfMrJDNWqcq8bW6OhWgZd6XUi-F1UI&libraries=places"></script>
<script src="/jquery.geocomplete.min.js"></script>
<script>
  $('#address-lookup').geocomplete({ details: "form" }).bind("geocode:result", function(event, result){
    console.log(result);
    if($('#street_number').val() !== "") {
      $('#address-lookup').removeClass('is-invalid');
      $('#address-lookup').addClass('is-valid');
      console.log($('#street_number').val());
    } else {
      $('#address-lookup').removeClass('is-valid');
      $('#address-lookup').addClass('is-invalid');
      console.log($('#street_number').val());
    };
  });
</script>
<script>
  $('#button1').on('click', function(){
    $('#form1').submit();
  });
</script>

app/views/performer/social_links.html.erb
<%= render 'dashboard/shared/header2', header: 'Social Links', link: @performer.id, type: 'performer' %>
<div class="container">
  <%= form_for(@performer, :html => {role: "form", id: "form1"}, url: edit_performer_social_links_url(@performer.id)) do |f| %>
  <!-- Facebook Page -->
    <div class="form-group mb-3">
      <label for="facebook">Facebook Page</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1"><img src="/images/facebook.svg" alt="Facebook" width="20px"></span>
        </div>
        <input type="text" placeholder="Link" aria-label="facebook" aria-describedby="basic-addon1" name="facebook" id="facebook" class="form-control
        <% if !@social_links.find_by_channel('Facebook').nil? %>is-valid " value="<%= @social_links.find_by_channel('Facebook').url %><% end %>">
      </div>
      <small id="basic-addon1" class="form-text text-muted">Die passende Facebook Gruppe.</small>
    </div>

  <!-- Instagram -->

    <div class="form-group mb-3">
      <label for="instagram">Instagram Akkount</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon2"><img src="/images/instagram.svg" alt="Instagram" width="20px"></span>
      </div>
      <input type="text" placeholder="Username" aria-label="instagram" id="instagram" aria-describedby="basic-addon2" name="instagram" class="form-control
      <% if !@social_links.find_by_channel('Instagram').nil? %>is-valid" value="<%= @social_links.find_by_channel('Instagram').url %><% end %>">
    </div>
    </div>

  <!-- YouTube Video -->
    <div class="form-group mb-3">
      <label for="youtube">YouTube Video</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon3"><img src="/images/youtube.svg" alt="YouTube" width="20px"></span>
        </div>
        <input type="text" placeholder="Videolink" aria-label="youtube" id="youtube" aria-describedby="basic-addon3" name="youtube" class="form-control
        <% if !@social_links.find_by_channel('YouTube').nil? %>is-valid" value="<%= @social_links.find_by_channel('YouTube').url %><% end %> ">    
      </div>
    </div>

  <!-- SoundCloud -->
    <div class="form-group mb-3">
      <label for="soundcloud">SoundCloud Link</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon4"><img src="/images/soundcloud.svg" alt="Soundcloud" width="20px"></span>
        </div>
        <input type="text" placeholder="http://www.soundcloud.com/username" aria-label="soundcloud" id="soundcloud" aria-describedby="basic-addon4" name="soundcloud" class="form-control
        <% if !@social_links.find_by_channel('SoundCloud').nil? %>is-valid" value="<%= @social_links.find_by_channel('SoundCloud').url %><% end %>">
      </div>
    </div>

  <!-- Webseite -->
    <div class="form-group mb-3">
      <label for="webseite">Webseite</label>
      <div class="input-group" style="flex-wrap: nowrap; display: flex;">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon4"><img src="/images/website.svg" alt="Website" width="20px"></span>
        </div>
        <input type="text" placeholder="www.beispiel.de" aria-label="webseite" id="webseite" aria-describedby="basic-addon4" name="webseite" class="form-control
        <% if !@social_links.find_by_channel('Webseite').nil? %>is-valid" value="<%= @social_links.find_by_channel('Webseite').url %><% end %>">
      </div>
    </div>
  
  <% end %>
</div>
<div class="footer">
  <a href='' class="footer-link" id="button1">Aktualisieren</a> 
</div>
<script>
  $('#button1').on('click', function(){
    $('#form1').submit();
  });
</script>