config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :user do
    end
  end
  
  root 'dashboard#index'
  
  get 'first_login' => 'dashboard#first_login', as: :first_login
  get 'first_event' => 'dashboard#first_event', as: :first_event
  
  get 'l/show/:id' => 'dashboard#show_location', as: :show_location
  get 'p/show/:id' => 'dashboard#show_performer', as: :show_performer
  get 'o/show/:id' => 'dashboard#show_organizer', as: :show_organizer
  
  get 'l/:id/edit_images' => 'location#edit_images'
  get 'p/:id/edit_images' => 'performer#edit_images'
  get 'e/:id/edit_images' => 'event#edit_images'
  get 'o/:id/edit_images' => 'organizer#edit_images'
  get 'o/:id/edit_profile_image' => 'organizer#edit_profile_image'
  
  get 'l/:id/events' => 'location#events'
  get 'p/:id/events' => 'performer#events'
  get 'o/:id/events' => 'organizer#events'
  
  get 'l/:id/edit_informations' => 'location#edit_informations'
  get 'p/:id/edit_informations' => 'performer#edit_informations'
  get 'o/:id/edit_informations' => 'organizer#edit_informations'
  get 'e/:id/edit' => 'event#edit'

  patch 'l/:id/edit_informations' => 'location#update_informations', as: :edit_location_informations
  patch 'p/:id/edit_informations' => 'performer#update_informations', as: :edit_performer_informations
  patch 'o/:id/edit_informations' => 'organizer#update_informations', as: :edit_organizer_informations
  patch 'e/:id/edit' => 'event#update', as: :update_event
  
  get 'l/:id/share' => 'location#share'
  get 'p/:id/share' => 'performer#share'
  get 'o/:id/share' => 'organizer#share'
  get 'e/:id/share' => 'event#share'
  
  get 'l/:id/social_links' => 'location#social_links'
  get 'p/:id/social_links' => 'performer#social_links'
  get 'o/:id/social_links' => 'organizer#social_links'
  get 'e/:id/social_links' => 'event#social_links'
  
  get 'p/:id/requests' => 'performer#requests'
  get 'o/:id/requests' => 'organizer#requests'
  
  get 'e/:id/tickets' => 'event#tickets'
  get 'e/:id/performer' => 'event#edit_performer'
  get 'e/:id/premium' => 'event#edit_premium'
  get 'e/:id/statistiken' => 'event#statistiken'
  patch 'e/:id/toggle-online' => 'event#toggle_online'
  
  
  patch 'l/:id/social_links' => 'location#edit_social_links', as: :edit_location_social_links
  patch 'p/:id/social_links' => 'performer#edit_social_links', as: :edit_performer_social_links
  patch 'o/:id/social_links' => 'organizer#edit_social_links', as: :edit_organizer_social_links
  patch 'e/:id/social_links' => 'event#update_social_links', as: :update_event_social_links
  
  get 'l/:id/opening_hours' => 'location#opening_hours'
  patch 'l/:id/opening_hours' => 'location#update_opening_hours', as: :update_opening_hours
  
  post 'l/create_from_event' => 'location#create_from_event', as: :create_location_from_event
  get 'l/search_from_event' => 'location#search_from_event'

  post 'p/create_from_event' => 'performer#create_from_event', as: :create_performer_from_event
  get 'p/search_from_event' => 'performer#search_from_event'
  post 'performer-request' => 'performer#performer_request'
  patch 'performer-request/:id' => 'performer#update_performer_request'
  delete 'delete-performer-request' => 'performer#delete_performer_request', as: :delete_performer_request
  
  post 'o/create_from_event' => 'organizer#create_from_event', as: :create_organizer_from_event
  get 'o/search_from_event' => 'organizer#search_from_event'
  post 'organizer-request' => 'organizer#organizer_request'
  patch 'organizer-request/:id' => 'organizer#update_organizer_request'
  delete 'delete-organizer-request' => 'organizer#delete_organizer_request', as: :delete_organizer_request
  
  
  get 'einstellungen' => 'dashboard#settings'
  get 'einstellungen/profiles' => 'dashboard#profiles'
  get 'einstellungen/abo' => 'dashboard#abo'
  get 'einstellungen/abo/plans' => 'payment#plans'
  get 'einstellungen/abo/bezahlen' => 'payment#payment_method'
  get 'statistiken' => 'dashboard#statistiken'
  get 'select_abo' => 'payment#select_abo', as: :select_abo
  
  get 'success' => 'payment#success'  
  get 'cancel' => 'payment#cancel'
  
  post 'webhook/customer_updated' => 'payment#customer_updated'
  post 'webhook/charge' => 'payment#charge'
  post 'webhook/invoice_created' => 'payment#invoice_created'
  
  post 'pageview' => 'page_view#create'
  
  get 'neue-location' => 'dashboard#new_location'
  get 'neuer-performer' =>'dashboard#new_performer'
  get 'neues-event' => 'dashboard#new_event'
  get 'neuer-organizer' => 'dashboard#new_organizer'
  
  get 'fertigstellen/:type/:id' => 'dashboard#fertigstellen'
  
  get 'event-bearbeiten/:id' => 'dashboard#edit_event'
  get 'performer-bearbeiten/:id' => 'dashboard#edit_performer'

  post 'event/create' => 'event#create_event1', as: :create_event1
  post 'event/:id/add_images' =>  'event#add_images'
  post 'event/select-plan/:id' => 'event#select_plan'
  patch 'event/create3/:id' =>  'event#create_event3', as: :create_event3
  
  post 'create-ticket' =>  'ticket#create', as: :create_ticket
  
  post 'create-link' =>  'social_link#create', as: :create_link
  
  post 'location/create' => 'location#create_location1', as: :create_location1
  post 'location/:id/add_images' =>  'location#add_images'
  patch 'location/create3/:id' =>  'location#create_location3', as: :create_location3
  
  post 'performer/create' => 'performer#create_performer1', as: :create_performer1
  post 'performer/:id/add_image' =>  'performer#add_image'
  
  post 'organizer/create' => 'organizer#create_organizer1', as: :create_organizer1
  post 'organizer/:id/add_image' =>  'organizer#add_image'
  post 'organizer/:id/add_profile_image' =>  'organizer#add_profile_image'
  
  post 'opening_hour/create' => 'opening_hour#create'
  post 'social_link/create' => 'social_link#create'
  post 'ticket/create' => 'ticket#create'
  
  get 'performer/search' => 'event#search_performer'
  post 'performer/invite' => 'event#invite_performer', as: :invite_performer
  post 'performer/create' => 'performer#create'
  
  get 'organizer/search' => 'event#search_organizer'
  post 'organizer/invite' => 'event#invite_organizer', as: :invite_organizer
  post 'organizer/create' => 'organizer#create'
  
  patch 'event/edit/:id' => 'event#edit', as: :edit_event
  patch 'location/edit/:id' => 'location#edit'
  patch 'opening_hour/edit/:id' => 'opening_hour#edit'
  patch 'social_link/edit/:id' => 'social_link#edit'
  patch 'ticket/edit/:id' => 'ticket#edit'
  patch 'performer/edit/:id' => 'performer#edit', as: :edit_performer
  
  delete 'event/delete/:id' => 'event#delete', as: :delete_event
  delete 'location/delete/:id' => 'location#delete', as: :delete_location
  delete 'delete_image/:id' => 'dashboard#delete_image', as: :delete_image
  delete 'opening_hour/delete/:id' => 'opening_hour#delete'
  delete 'social_link/delete/:id' => 'social_link#destroy', as: :destroy_link
  delete 'ticket/delete/:id' => 'ticket#destroy', as: :destroy_ticket
  delete 'performer/delete/:id' => 'performer#delete', as: :delete_performer
  delete 'organizer/delete/:id' => 'organizer#delete', as: :delete_organizer
  
  devise_for :users
  
  patch 'update_invoice_mail' => 'dashboard#invoice_email', as: :update_invoice_mail
  
  # Event, Location & Performer Views
  
  get 'location/:path' => 'public_view#location'
  get 'performer/:path' => 'public_view#performer'
  get 'organizer/:path' => 'public_view#organizer'
  get 'event/:path' => 'public_view#event'
  get 'event/:path/tickets' => 'public_view#tickets'
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController  
  before_action :authenticate_user!
  layout 'dashboard'
  
  def first_login
    
  end
  
  def first_event
    
  end
  
  def index
    finish_onboarding
    onboarding_done?
    
    @user = current_user
    
    if params[:profile] != nil
      if params[:type] == 'location'
        @profile = Location.find(params[:profile])
        @type = 'location'
      elsif params[:type] == 'performer'
        @profile = Performer.find(params[:profile])
        @type = 'performer'
      else
        @profile = Organizer.find(params[:profile])
        @type = 'organizer'
      end
    else 
      if @user.locations.any? 
        @profile = @user.locations.first
        @type = 'location'
      elsif @user.performers.any?
        @profile = @user.performers.first
        @type = 'performer'
      else
        @profile = @user.organizers.first
        @type = 'organizer'
      end
    end
  end
  
  def new_location
    barrier_locations
    
    @user = current_user
    @location = Location.new
    @resource = "Ihre Location"
  end
  
  def new_performer
    barrier_performer
    
    @user = current_user
    @performer = Performer.new
    @resource = "Ihr Performer"
  end
  
  def new_organizer  
    @user = current_user
    @organizer = Organizer.new
    @resource = "Ihr Organizer"
  end
  
  def new_event
    barrier_events
    
    if params[:profile] != nil
      if params[:type] == 'location'
        @location = Location.find(params[:profile])
        @profile = @location.id
        @type = 'location'
      elsif params[:type] == 'performer'
        @performer = Performer.find(params[:profile])
        @profile = @performer.id
        @type = 'performer'
      else
        @organizer = Organizer.find(params[:profile])
        @profile = @organizer.id
        @type = 'organizer'
      end
    end
    
    @user = current_user
    @event = Event.new
    @resource = "Ihre Veranstaltung"
    
  end
  
  def edit_event
    @event = Event.find(params[:id])
  end
  
  def edit_performer
    @performer = Performer.find(params[:id])
  end
  
  def show_location
    @profile = Location.find(params[:id])
    
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/show_location' }
    end
  end
  
  def show_performer
    @profile = Performer.find(params[:id])
    
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/show_performer' }
    end
  end
  
  def show_organizer
    @profile = Organizer.find(params[:id])
    
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/show_organizer' }
    end
  end
  
  def settings
    @user = current_user
  end
  
  def delete_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    respond_to do |format|
      format.js { render partial: 'dashboard/shared/image_destroyed' }
    end
  end
  
  def profiles
    @user = current_user
    
  end
  
  def abo
    @user = current_user    
  end
  
  def invoice_email
    @user = current_user
    @user.bill_per_email = !@user.bill_per_email
    if @user.save!
      respond_to do |format|
        format.js { render :js => "$('.toggle_check').toggleClass('active');" }
      end
    else
      respond_to do |format|
        format.js { render :js => "alert('danger', 'Es ist ein Fehler aufgetretten.')" }
      end
    end
  end
  
  def statistiken
    @user = current_user
  end
  
  def fertigstellen
    
    case params[:type]
      when 'p'
        @resource = Performer.find(params[:id])
        @header = 'Performer'
      when 'e'
        @resource = Event.find(params[:id])
        @header = 'Event'
      when 'l'
        @resource = Location.find(params[:id])
        @header = 'Location'
      when 'o'
        @resource = Organizer.find(params[:id])
        @header = 'Veranstalter'
    end
  end
  
private
  
  def has_profile?
    if !current_user.locations.any? && !current_user.performers.any?
      redirect_to first_login_path
    end
  end
  
  def finish_onboarding
    if params[:onboardingfinished]
      current_user.onboarding = true
      current_user.save!
    end
  end
  
  def onboarding_done?
    if !current_user.locations.any? && !current_user.performers.any? && !current_user.organizers.any?
      redirect_to first_login_path
      return
    else
      if current_user.onboarding != true
        if current_user.events.length == 0
          redirect_to first_event_path
        else
          redirect_to select_abo_path
        end
      end
    end
  end
  
  def barrier_locations
    case current_user.plan
      when "free"
        if current_user.locations.length > 0
          redirect_to 
        end
      when "Gold"
        if current_user.locations.length >= 10
          redirect_to 
        end
      when "Platin"
        return
    end
  end
  
  def barrier_performer
    case current_user.plan
      when "free"
        if current_user.performers.length > 3
          redirect_to 
        end
      when "Gold"
        if current_user.performers.length > 10
          redirect_to 
        end
      when "Platin"
        return
    end
  end
  
  def barrier_events
    case current_user.plan
      when "free"
        if current_user.events.length >= 3
          redirect_to 
        end
      when "Gold"
        if current_user.events.length >= 100
          redirect_to 
        end
      when "Platin"
      
    end
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/shared/_header.html.erb
<nav class="radr-navbar">
    <a id="back" href="/" style="display: none">      
      <svg width="10px" height="20px" viewBox="0 0 12 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <g transform="translate(-19.000000, -20.000000)" stroke="#000000">
                  <polyline points="30 20 20 30 30 40"></polyline>
              </g>
          </g>
      </svg>
    </a>
  
    <div class="dropdown-container">
      <span>        
          <svg width="16px" height="9px" viewBox="0 0 16 9" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin-right: 5px;">
              <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-114.000000, -26.000000)" fill="#000000" fill-rule="nonzero">
                      <g transform="translate(114.000000, 18.000000)">
                          <g transform="translate(8.000000, 12.500000) rotate(90.000000) translate(-8.000000, -12.500000) translate(3.500000, 5.000000)">
                              <polygon points="0 0.909375 0.9703125 0 9 7.5 0.9703125 15 0 14.0953125 7.0546875 7.5"></polygon>
                          </g>
                      </g>
                  </g>
              </g>
          </svg>
          <div id="profile-name"><%= @profile.name %></div>
        </span>
      <div class="dropdown">
        <ul class="dropdown-inner">
          <% @user.locations.each do |location| %>
            <li><%= button_to location.name, show_location_path(:id => location.id), :method => :get, :remote => true %></li>
          <% end %>
          <% @user.performers.each do |performer| %>
            <li><%= button_to performer.name, show_performer_path(:id => performer.id), :method => :get, :remote => true %></li>
          <% end %>
          <% @user.organizers.each do |organizer| %>
            <li><%= button_to organizer.name, show_organizer_path(:id => organizer.id), :method => :get, :remote => true %></li>
          <% end %>
          <li><a data-type="inbound-link" href="/neue-location">Location erstellen</a></li>
          <li><a data-type="inbound-link" href="/neuer-performer">Performer erstellen</a></li>
          <li><a data-type="inbound-link" href="/neuer-organizer">Veranstalter erstellen</a></li>
        </ul>
      </div>
    </div>
  
      <div class="menu">
        <div id="hamburger" class="hamburger-icon-container">                        
          <span id="top"></span>
          <span id="midleft"></span>
          <span id="midright"></span>
          <span id="bottom"></span>
        </div>
        
        <ul>
          <li><a data-type="inbound-link" href="/">Dashboard</a></li>
          <li><a data-type="inbound-link" href="/neue-location">Location erstellen</a></li>
          <li><a data-type="inbound-link" href="/statistiken">Statistiken</a></li>
          <li><a data-type="inbound-link" href="/einstellungen">Einstellungen</a></li>
          <li><%= link_to "Abmelden", destroy_user_session_path, :method => :delete %></li>
        </ul>
        
      </div>
</nav>
<script>
  $('#hamburger').on('click', function(){
    $('.menu').toggleClass('active');
  });
  
  $('.dropdown-container span').on('click', function(){
    if($('.dropdown-container').hasClass('active')) {    
      $('.dropdown-inner').slideUp();
      setTimeout(function () {      
         $('.dropdown-container').removeClass('active')       
      }, 350);
    } else {
      $('.dropdown-container').addClass('active');
      $('.dropdown-inner').slideDown().delay(300);
  }});
</script>

app/views/dashboard/shared/_header2.html.erb
<nav class="radr-navbar">
    <a id="back" href="/?profile=<%= link %>&type=<%= type %>" style="<% if link == '' %>display: none;<% end %>">      
      <svg width="10px" height="20px" viewBox="0 0 12 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <g transform="translate(-19.000000, -20.000000)" stroke="#000000">
                  <polyline points="30 20 20 30 30 40"></polyline>
              </g>
          </g>
      </svg>
    </a>
  
    <span class="centered"><%= header %></span>
  
      <div class="menu">
        <div id="hamburger" class="hamburger-icon-container">                        
          <span id="top"></span>
          <span id="midleft"></span>
          <span id="midright"></span>
          <span id="bottom"></span>
        </div>
        
        <ul>
          <li><a href="/" data-type="inbound-link">Dashboard</a></li>
          <li><a href="/neue-location" data-type="inbound-link">Neue Location</a></li>
          <li><a data-type="inbound-link" href="/statistiken">Statistiken</a></li>
          <li><a href="/einstellungen" data-type="inbound-link">Einstellungen</a></li>
          <li><%= link_to "Abmelden", destroy_user_session_path, :method => :delete %></li>
        </ul>
        
      </div>
</nav>
<script>
  $('#hamburger').on('click', function(){
    $('.menu').toggleClass('active');
  })
</script>

app/views/dashboard/shared/_header3.html.erb
<nav class="radr-navbar">
    <a id="back" href="javascript:history.back()">      
      <svg width="10px" height="20px" viewBox="0 0 12 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <g transform="translate(-19.000000, -20.000000)" stroke="#000000">
                  <polyline points="30 20 20 30 30 40"></polyline>
              </g>
          </g>
      </svg>
    </a>
  
    <span class="centered"><%= header %></span>
  
      <div class="menu">
        <div id="hamburger" class="hamburger-icon-container">                        
          <span id="top"></span>
          <span id="midleft"></span>
          <span id="midright"></span>
          <span id="bottom"></span>
        </div>
        
        <ul>
          <li><a href="/" data-type="inbound-link">Dashboard</a></li>
          <li><a href="/neue-location" data-type="inbound-link">Neue Location</a></li>
          <li><a data-type="inbound-link" href="/statistiken">Statistiken</a></li>
          <li><a href="/einstellungen" data-type="inbound-link">Einstellungen</a></li>
          <li><%= link_to "Abmelden", destroy_user_session_path, :method => :delete %></li>
        </ul>
        
      </div>
</nav>
<script>
  $('#hamburger').on('click', function(){
    $('.menu').toggleClass('active');
  })
</script>

app/views/dashboard/shared/_image_destroyed.js.erb
$('[data-id="<%= @image.id %>"]').remove();

app/views/dashboard/shared/_show_location.js.erb
$('#container').html("<%= j(render 'dashboard/shared/show_location.html') %>");
$('#profile-name').html("<%= @profile.name %>");
$('.dropdown-inner').slideUp();
setTimeout(function () {      
   $('.dropdown-container').removeClass('active')       
}, 350);

app/views/dashboard/shared/_show_organizer.js.erb
$('#container').html("<%= j(render 'dashboard/shared/show_organizer.html') %>");
$('#profile-name').html("<%= @profile.name %>");
$('.dropdown-inner').slideUp();
setTimeout(function () {      
   $('.dropdown-container').removeClass('active')       
}, 350);

app/views/dashboard/shared/_show_performer.js.erb
$('#container').html("<%= j(render 'dashboard/shared/show_performer.html') %>");
$('#profile-name').html("<%= @profile.name %>");
$('.dropdown-inner').slideUp();
setTimeout(function () {      
   $('.dropdown-container').removeClass('active')       
}, 350);